name = "Luminescent"
uuid = "60a98398-2d19-4130-ae20-63172a4a42f2"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "1.0.0"

[deps]
ArrayPadding = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Jello = "6872b481-e419-48a0-81d2-be4ee5684529"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Porcupine = "3b53a3d7-3f34-4bba-8df2-4717a8b1e972"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Zygote = "0.6"
